### ISSUE TITLE
Error 7 after adding to search paths

### ISSUE THREAD

**Issue by jmkokott** [LabVIEW-DCAF/Scaling#6]
Error 7 occurred at Invoke Node in PL_class cache.lvlib:Read Class Ancestry Without Loading.vi->PL_class cache.lvlib:discover class type.vi->PL_class cache.lvlib:identify new classes.vi->Standard Editor.lvlib:Configuration Utility.vi

**Comment by pollockm** [comment]
@jmkokott I can no longer reproduce this error - I believe that it has been fixed.
